apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb-config
data:
  initdb.sql: |
  CREATE USER appadmin with ENCRYPTED PASSWORD 'Superadminuser';
  ALTER ROLE appadmin WITH SUPERUSER;
  CREATE DATABASE users_db;
  grant all privileges on database users_db to appadmin;

---
apiVersion: v1
kind: Secret
metadata:
  name: ps-db-secret
type: kubernetes.io/basic-auth
stringData:
  password: Superadminuser

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ps-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/psdb_data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ps-db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi   
