"""updated course_of_interest

Revision ID: 58bcc491d88a
Revises: 8334ed02629a
Create Date: 2025-03-13 21:34:09.091752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58bcc491d88a'
down_revision = '8334ed02629a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('course_of_interest', sa.String(), nullable=False))
    op.drop_column('user', 'course_of_intrest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('course_of_intrest', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'course_of_interest')
    # ### end Alembic commands ###
